### ISSUE TITLE
I found a small bug 

### ISSUE THREAD

**Issue by leialbert** [nickbasile/comments-demo#5]
Good afternoon, Nick Basile.
Thank you for your blog , i had learnt a lot . I found a small bug on the first post of Building A Comments System With Vue.js, Laravel, and Tailwind CSS Part I. 
Here is your original code:
```
//Template
 <div>
    <div>
        <h2>Comments</h2>
    </div>
    <textarea v-model="data.body"
              placeholder="Add a comment"
              class="border">
    </textarea>
    <div>
        <button @click="saveComment">Save</button>
        <button>Cancel</button>
    </div>
</div>

//Script
saveComment() {
    let newComment = {
        id: this.comments[this.comments.length - 1].id + 1,
        body: this.data.body,
        edited: false,
        created_at: new Date().toLocaleString(),
        author: {
            id: this.user.id,
            name: this.user.name,
        }
    }

    this.comments.push(newComment);
    
    this.data.body = '';
}
```
We should change the `data` to `comments`. if we do not do that ,we will get an error and the browser will show nothing.
![image](https://user-images.githubusercontent.com/46070462/52257310-4fd79c00-2955-11e9-81be-86c61328e470.png)
I had changed my code like below:
```
// template
<div>
            <div>
                <h2>Comments</h2>
            </div>
            <textarea v-model="comments.body"
                placeholder="Add a comment"
                class="border">
              </textarea>
            <div>
                <button @click="saveComment">Save</button>
                <button>Cancel</button>
            </div>
        </div>
// script
saveComment() {
                let newComment = {
                    id: this.comments[this.comments.length - 1].id + 1,
                    body: this.comments.body,
                    edited: false,
                    created_at: new Date().toLocaleString(),
                    author: {
                        id: this.user.id,
                        name: this.user.name,
                    }
                }

                this.comments.push(newComment);

                this.comments.body = '';
            },
```
And also I am using the latest laravel 5.7 , we don't have asserts folder in my resources directory.
![image](https://user-images.githubusercontent.com/46070462/52257414-bb216e00-2955-11e9-8ea9-360e1973de75.png)

Thank you very much , wish this can help others .

**Comment by nickbasile** [comment]
Hi @leienshu, thanks for commenting! The `comments` array is where we're storing our array of comments, so we don't really want to use that for our new comment's body because then we'd be mixing our existing comments with our new comment's data.

It's hard for me to say because I can't see all of your code, but it seems like the error message you received is because there is no `data` property initialized in your Vue component's `data`. So, it should look something like this:

```
data: function() {
  return {
    state: 'default',
    data: {
      body: ''
    },
    comments: []
  }
},
```

Hope that helps!
