### ISSUE TITLE
Implement diffForHumans() for comment date

### ISSUE THREAD

**Issue by itsmysterybox** [nickbasile/comments-demo#6]
Hello @nickbasile Thanks for your awesome post.

I want to use `diffForHumans()` on `created_at` column. How can I do that on the collection? This is how comments are fetched.
```
$comments = Comment::with('author')
            ->orderByDesc('id')
            ->get();
```

**Comment by nickbasile** [comment]
Hi @itsmysterybox!

There are a couple of ways to do this, but the easiest way would be to map the collection.

```
$comments->map(function($comment) {
    $comment->created_at_diffed = \Carbon\Carbon::parse($comment->created_at)->diffForHumans();
    return $comment;
});
```
